workflows:
  ios-unsigned-build:
    name: iOS Unsigned Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..

      - name: Build unsigned iOS .app
        script: |
          flutter build ios --no-codesign --release

      - name: Package .app into .ipa
        script: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r unsigned.ipa Payload
          rm -rf Payload

    artifacts:
      - unsigned.ipa
