workflows:
  ios-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    # integrations:
    #   app_store_connect: Ateam-Splace
    environment:
    #   ios_signing:
    #     distribution_type: app_store
    #     bundle_identifier: com.splacebar.app.splace
      # vars:
      #   APP_ID: com.splacebar.app.splace
      flutter: stable
    # xcode: 16.2
    # cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      # - name: Set up code signing settings on Xcode project
      #   script: xcode-project use-profiles
      - name: Build Android
        script: flutter build apk --release
      # - name: Flutter build ipa and automatic versioning
      #   script: |
      #     flutter build ipa --release \
      #     --build-name=1.0.0 \
      #     --build-number=$(($(app-store-connect
      #     get-latest-testflight-build-number --platform=IOS "$APP_ID") + 1)) \
      #     --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - build/**/outputs/**/*.aab
      - build/app/outputs/flutter-apk/*.apk  
    publishing:
    #   app_store_connect:
    #     auth: integration
    #     submit_to_test_flight: true
    #     beta_groups:
    #       - Splacebar Internal Team
      email:
        recipients:
          - anugrahkorembeth.ak@gmail.com
        notify:
          success: true
          failure: false

